# Generated by Django 6.1.1 on 2026-10-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_ml', models.PositiveIntegerField()),
                ('launch_year', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='perfume_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumes.brand')),
                ('category', models.ManyToManyField(to='perfumes.category')),
            ],
        ),
    ]
